on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

name: Go
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x, 1.19.x, 1.20.x, 1.21.x]
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Run tests
      run: |
        go test -race -count=5 ./...

    - name: Shuffle tests
      if: startsWith(matrix.go-version, '1.21')
      run: |
        go test -shuffle=on ./...
