on: [push, pull_request]

name: Go
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        go test -race -count=5 ./...